### ISSUE TITLE
mvn verify -Pmac64,mars fails.

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#288]
also Linux64,mars fails.
mvn verify -Pmac64,luna  works fine.
Below is my comand dump.

bash-4.1$ mvn verify -Pmac64,mars
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: com.github.brodykenrick.arduino-eclipse-plugin:it.baeyens.arduino.core.nl1:2.4.0-SNAPSHOT @ /home/jan/workspaces/eclipse_plugin/ArduinoPluginDevelopment/it.baeyens.arduino.core.nl1/pom.xml
[INFO] Adding repository http://download.eclipse.org/technology/nebula/snapshot
[INFO] Resolving dependencies of MavenProject: com.github.brodykenrick.arduino-eclipse-plugin:it.baeyens.arduino.core.nl1:2.4.0-SNAPSHOT @ /home/jan/workspaces/eclipse_plugin/ArduinoPluginDevelopment/it.baeyens.arduino.core.nl1/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.ws=cocoa, osgi.os=macosx, osgi.arch=x86_64, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: it.baeyens.arduino.core.nl1 2.4.0.qualifier
[ERROR]   Missing requirement: it.baeyens.arduino.core 2.4.0.qualifier requires 'bundle org.eclipse.core.runtime 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: it.baeyens.arduino.core.nl1 2.4.0.qualifier depends on: bundle it.baeyens.arduino.core 2.1.0
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.jface.text 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.cdt 8.5.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.osgi 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.internal.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.managedbuilder.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.equinox.security 1.1.100.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.apache.commons.io 1.2.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.language.settings.providers 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.extension 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.util 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.ui.newui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.utils 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core 3.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core.security 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.events 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.identity 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.dialogs 0.0.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.jface.text 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.cdt 8.5.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.osgi 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.internal.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.managedbuilder.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.equinox.security 1.1.100.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.apache.commons.io 1.2.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.language.settings.providers 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.extension 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.util 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.ui.newui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.utils 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core 3.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core.security 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.events 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.identity 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.dialogs 0.0.0.; No solution found because the problem is unsatisfiable.]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:164)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.jface.text 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.cdt 8.5.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to bundle org.eclipse.osgi 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.internal.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.common 2.4.0.qualifier to package org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.resources 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.managedbuilder.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.core.filesystem 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.ide 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.equinox.security 1.1.100.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to bundle org.eclipse.ui.navigator 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.apache.commons.io 1.2.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.envvar 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.language.settings.providers 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.extension 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.core.settings.model.util 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.ui.newui 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.cdt.utils 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core 3.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.core.security 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.events 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ecf.filetransfer.identity 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.console 0.0.0.; Unable to satisfy dependency from it.baeyens.arduino.core 2.4.0.qualifier to package org.eclipse.ui.dialogs 0.0.0.; No solution found because the problem is unsatisfiable.]
	at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
	at org.eclipse.tycho.p2.resolver.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
	at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
	at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:157)
	at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:107)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.doResolveDependencies(P2TargetPlatformResolver.java:348)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.resolveDependencies(P2TargetPlatformResolver.java:321)
	at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:109)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:271)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
bash-4.1$

**Comment by jantje** [comment]
this is fixed now on my system
